# Generated by Django 4.2.3 on 2023-08-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aboutme',
            field=models.CharField(default='No Information', max_length=1024),
        ),
    ]
